version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: provincias
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red-interna

  web1:
    build: .
    container_name: web1
    environment:
      DB_HOST: db
      DB_NAME: provincias
      DB_USER: user
      DB_PASS: pass
    depends_on:
      - db
    networks:
      - red-interna

  web2:
    build: .
    container_name: web2
    environment:
      DB_HOST: db
      DB_NAME: provincias
      DB_USER: user
      DB_PASS: pass
    depends_on:
      - db
    networks:
      - red-interna

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
    networks:
      - red-interna

volumes:
  pgdata:

networks:
  red-interna:
    driver: bridge
